version: "3.8"

services:
  pg_tileserv:
    image: pramsey/pg_tileserv
    container_name: pg_tileserv
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PG_TILESERV_WEBROOT: /tiles
    ports:
      - "7800:7800"
    restart: unless-stopped

  pg_featureserv:
    image: pramsey/pg_featureserv
    container_name: pg_featureserv
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PG_FEATURESERV_WEBROOT: /features
    ports:
      - "9000:9000"
    restart: unless-stopped
